// Codegen: reads script-globals-types.ts and emits script-globals.dts
// (a text artifact loaded into Monaco via addExtraLib at runtime).
//
// Why .dts (no `.ts` suffix): TypeScript's tsconfig.json has
// `"include": ["src"]`. A real .d.ts inside src/ would be picked up as
// ambient declarations and would silently grant the entire client
// codebase access to a `scene` global — masking real bugs. The custom
// extension keeps the file invisible to TypeScript and visible only to
// Vite's `?raw` text loader.
//
// Run: `npm run gen:script-globals --workspace=packages/client`.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import * as ts from 'typescript';

const here          = dirname(fileURLToPath(import.meta.url));
const SOURCE_PATH   = resolve(here, '../src/scripting/script-globals-types.ts');
const TARGET_PATH   = resolve(here, '../src/scripting/script-globals.dts');

interface Member {
  text: string;
}

const src      = readFileSync(SOURCE_PATH, 'utf-8');
const sf       = ts.createSourceFile(SOURCE_PATH, src, ts.ScriptTarget.ES2022, true);
const printer  = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });

const out: string[] = [];
const declared: string[] = [];

out.push('// AUTO-GENERATED by packages/client/scripts/gen-script-globals.ts.');
out.push('// Do not edit by hand. Source of truth: script-globals-types.ts.');
out.push('');

for (const stmt of sf.statements) {
  if (ts.isInterfaceDeclaration(stmt)) {
    const name = unprefix(stmt.name.text);
    declared.push(name);
    const printed = stripLeadingTrivia(printer.printNode(ts.EmitHint.Unspecified, stmt, sf));
    out.push(rewrite(printed.replace(/^export\s+/m, '')));
    out.push('');
    continue;
  }
  if (ts.isTypeAliasDeclaration(stmt)) {
    const name = unprefix(stmt.name.text);
    declared.push(name);
    const printed = stripLeadingTrivia(printer.printNode(ts.EmitHint.Unspecified, stmt, sf));
    out.push(rewrite(printed.replace(/^export\s+/m, '')));
    out.push('');
    continue;
  }
  if (ts.isClassDeclaration(stmt) && stmt.name) {
    const name = unprefix(stmt.name.text);
    declared.push(name);
    const members: Member[] = [];
    for (const member of stmt.members) {
      // PropertyDeclaration: drop modifiers we don't need (declare).
      if (ts.isPropertyDeclaration(member) && member.name) {
        const propName = (member.name as ts.Identifier).text;
        const typeText = member.type ? rewrite(member.type.getText(sf)) : 'unknown';
        const ro = member.modifiers?.some((m) => m.kind === ts.SyntaxKind.ReadonlyKeyword) ? 'readonly ' : '';
        members.push({ text: `  ${ro}${propName}: ${typeText};` });
        continue;
      }
      // MethodDeclaration: emit signature without body.
      if (ts.isMethodDeclaration(member) && member.name) {
        const methodName = (member.name as ts.Identifier).text;
        const params = member.parameters
          .map((p) => {
            const pname    = (p.name as ts.Identifier).text;
            const ptype    = p.type ? rewrite(p.type.getText(sf)) : 'unknown';
            const optional = p.questionToken ? '?' : '';
            return `${pname}${optional}: ${ptype}`;
          })
          .join(', ');
        const ret = member.type ? rewrite(member.type.getText(sf)) : 'void';
        members.push({ text: `  ${methodName}(${params}): ${ret};` });
        continue;
      }
    }
    out.push(`declare class ${name} {`);
    for (const m of members) out.push(m.text);
    out.push('}');
    out.push('');
    continue;
  }
}

// Global injection block — the names the SES Compartment binds at script
// load time, per ScriptHost.runScript. `game` is bound only by
// ScriptHost.runOneShot (the host's one-time Console panel) but is
// declared here unconditionally so both editors get the same autocomplete
// surface; in the main editor it's effectively unused.
out.push('declare global {');
if (declared.includes('SceneFacade'))
  out.push('  var scene: SceneFacade;');
if (declared.includes('Game')) {
  out.push('  var Game: typeof Game;');
  out.push('  var game: Game | null;');
}
out.push("  var console: Pick<Console, 'log' | 'error' | 'warn' | 'info' | 'debug'>;");
out.push('}');
out.push('');

writeFileSync(TARGET_PATH, out.join('\n'));
console.log(`wrote ${TARGET_PATH}`);

function unprefix(name: string): string {
  return name.startsWith('Editor') ? name.slice('Editor'.length) : name;
}

function rewrite(text: string): string {
  return text.replace(/Editor([A-Z])/g, '$1');
}

// The TS printer attaches the *previous* node's trailing comments to the
// current node when the source has them adjacent. For our simple file
// that means doc comments leak between exports. Strip any `//` lines
// that appear before the first non-comment line.
function stripLeadingTrivia(text: string): string {
  const lines = text.split('\n');
  let i = 0;
  while (i < lines.length && /^\s*\/\//.test(lines[i])) i += 1;
  return lines.slice(i).join('\n');
}
