// OAuth `state` parameter codec. Packs `{ returnUrl, nonce }` into a
// URL-safe base64 string and unpacks/validates the same on callback. The
// nonce is generated by the caller (not here) so the caller can stash the
// expected value in memory and check it on the return leg.

import { base64UrlDecode, base64UrlEncode } from './base64url';

export interface StatePayload {
  returnUrl: string;
  nonce:     string;
}

export function encodeState(payload: StatePayload): string {
  const json  = JSON.stringify(payload);
  const bytes = new TextEncoder().encode(json);
  return base64UrlEncode(bytes);
}

export function decodeState(input: string): StatePayload | null {
  if (typeof input !== 'string' || input === '') return null;
  let bytes: Uint8Array;
  try {
    bytes = base64UrlDecode(input);
  } catch {
    return null;
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(new TextDecoder().decode(bytes));
  } catch {
    return null;
  }
  if (parsed === null || typeof parsed !== 'object') return null;
  const r = parsed as Record<string, unknown>;
  if (typeof r.returnUrl !== 'string' || r.returnUrl === '') return null;
  if (typeof r.nonce     !== 'string' || r.nonce     === '') return null;
  return { returnUrl: r.returnUrl, nonce: r.nonce };
}

export function generateNonce(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return base64UrlEncode(bytes);
}
